# fly.toml app configuration file generated for modelfight on 2023-07-21T14:34:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "modelfight"
primary_region = "ewr"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "llmboxing.com"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
